# Generated by Django 4.0.1 on 2022-01-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_alter_proposta_cliente_delete_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-data'], 'verbose_name': 'Uma Proposta', 'verbose_name_plural': 'Propostas'},
        ),
    ]
