# Generated by Django 4.0.1 on 2022-01-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='dias_visita',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='dias_visita',
            field=models.ManyToManyField(to='dashboard.DiasVisita'),
        ),
    ]
