# Generated by Django 4.0.1 on 2022-01-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horarios',
            field=models.ManyToManyField(to='dashboard.Horario'),
        ),
    ]
